package bhaashik.morph.util;

import bhaashik.morph.encoding.WXConverter;
import java.io.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Converts Apertium monodix files from WX notation to native Indic scripts.
 * This is standard practice in Apertium for Indic languages - providing both
 * WX (ASCII-based) and native script versions.
 *
 * The converter preserves all XML structure and only converts text content
 * in specific locations:
 * - Text inside <i> tags (stems)
 * - Text inside <l> and <r> tags (left/right paradigm sides)
 * - lm attribute values (lemmas)
 * - pardef n attribute values (paradigm names)
 *
 * Tag names, attribute names, and symbol definitions remain unchanged.
 */
public class MonodixScriptConverter {

    private final WXConverter converter;

    public MonodixScriptConverter() {
        this.converter = new WXConverter();
    }

    /**
     * Convert a monodix file from WX to the specified target script.
     *
     * @param inputFile WX-based monodix file
     * @param outputFile Output file for native script version
     * @param targetScript Target script (e.g., "Devanagari", "Bengali", "Gujarati")
     * @throws IOException if file operations fail
     */
    public void convertFile(File inputFile, File outputFile, String targetScript) throws IOException {
        System.out.println("\n=== Converting Monodix to " + targetScript + " ===");
        System.out.println("Input:  " + inputFile.getAbsolutePath());
        System.out.println("Output: " + outputFile.getAbsolutePath());

        // Read entire file
        StringBuilder content = new StringBuilder();
        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(new FileInputStream(inputFile), "UTF-8"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                content.append(line).append("\n");
            }
        }

        String originalContent = content.toString();

        // Convert content
        String convertedContent = convertMonodixContent(originalContent, targetScript);

        // Write to output file
        try (BufferedWriter writer = new BufferedWriter(
                new OutputStreamWriter(new FileOutputStream(outputFile), "UTF-8"))) {
            writer.write(convertedContent);
        }

        System.out.println("✓ Conversion complete!");
        System.out.println("  Input size:  " + originalContent.length() + " characters");
        System.out.println("  Output size: " + convertedContent.length() + " characters");
    }

    /**
     * Convert monodix XML content from WX to target script.
     * Only converts text content, not XML structure.
     */
    private String convertMonodixContent(String content, String targetScript) {
        // Update XML comment to indicate script
        content = content.replaceFirst(
            "(<!-- Morphological dictionary generated by Bhaashik Morph API -->)",
            "$1\n<!-- Script: " + targetScript + " (converted from WX notation) -->"
        );

        // Update Script comment if present
        content = content.replaceFirst(
            "<!-- Script: WX -->",
            "<!-- Script: " + targetScript + " (WX) -->"
        );

        // Convert text inside <i> tags (stems)
        content = convertTagContent(content, "i", targetScript);

        // Convert text inside <l> tags (left side of paradigm pairs)
        content = convertTagContent(content, "l", targetScript);

        // Convert text inside <r> tags (right side - but NOT symbol tags)
        content = convertRTagContent(content, targetScript);

        // Convert lm attribute values (lemmas)
        content = convertAttribute(content, "lm", targetScript);

        // Convert pardef n attribute values (paradigm names - stems and lemma parts)
        content = convertPardefNames(content, targetScript);

        return content;
    }

    /**
     * Convert text content inside XML tags.
     */
    private String convertTagContent(String content, String tagName, String targetScript) {
        Pattern pattern = Pattern.compile("<" + tagName + ">([^<]*)</" + tagName + ">");
        Matcher matcher = pattern.matcher(content);

        StringBuffer result = new StringBuffer();
        while (matcher.find()) {
            String textContent = matcher.group(1);
            String converted = converter.convert(textContent, "WX", targetScript);
            matcher.appendReplacement(result,
                "<" + tagName + ">" + Matcher.quoteReplacement(converted) + "</" + tagName + ">");
        }
        matcher.appendTail(result);

        return result.toString();
    }

    /**
     * Convert text inside <r> tags, but preserve <s n="..."/> symbol tags.
     */
    private String convertRTagContent(String content, String targetScript) {
        Pattern pattern = Pattern.compile("<r>(.*?)</r>", Pattern.DOTALL);
        Matcher matcher = pattern.matcher(content);

        StringBuffer result = new StringBuffer();
        while (matcher.find()) {
            String rContent = matcher.group(1);

            // Split into text and symbol tags
            // Convert only the text portions, not the <s n="..."/> tags
            String converted = convertRContentParts(rContent, targetScript);

            matcher.appendReplacement(result,
                "<r>" + Matcher.quoteReplacement(converted) + "</r>");
        }
        matcher.appendTail(result);

        return result.toString();
    }

    /**
     * Convert text parts in <r> content while preserving <s> tags.
     */
    private String convertRContentParts(String rContent, String targetScript) {
        // Pattern to match <s n="..."/> tags
        Pattern symbolPattern = Pattern.compile("<s n=\"[^\"]*\"/>");
        Matcher symbolMatcher = symbolPattern.matcher(rContent);

        // Find all symbol tags and their positions
        StringBuilder result = new StringBuilder();
        int lastEnd = 0;

        while (symbolMatcher.find()) {
            // Convert text before this symbol tag
            String textBefore = rContent.substring(lastEnd, symbolMatcher.start());
            if (!textBefore.isEmpty()) {
                String converted = converter.convert(textBefore, "WX", targetScript);
                result.append(converted);
            }

            // Keep the symbol tag as-is
            result.append(symbolMatcher.group());
            lastEnd = symbolMatcher.end();
        }

        // Convert remaining text after last symbol tag
        if (lastEnd < rContent.length()) {
            String textAfter = rContent.substring(lastEnd);
            if (!textAfter.isEmpty()) {
                String converted = converter.convert(textAfter, "WX", targetScript);
                result.append(converted);
            }
        }

        return result.toString();
    }

    /**
     * Convert XML attribute values.
     */
    private String convertAttribute(String content, String attrName, String targetScript) {
        Pattern pattern = Pattern.compile(attrName + "=\"([^\"]*)\"");
        Matcher matcher = pattern.matcher(content);

        StringBuffer result = new StringBuffer();
        while (matcher.find()) {
            String attrValue = matcher.group(1);
            String converted = converter.convert(attrValue, "WX", targetScript);
            // Escape quotes in the converted value
            converted = converted.replace("\"", "&quot;");
            matcher.appendReplacement(result,
                attrName + "=\"" + Matcher.quoteReplacement(converted) + "\"");
        }
        matcher.appendTail(result);

        return result.toString();
    }

    /**
     * Convert pardef names which have format: stem/suffix__category or stem__category
     * Only convert the stem and suffix parts, not the category name.
     */
    private String convertPardefNames(String content, String targetScript) {
        Pattern pattern = Pattern.compile("<pardef n=\"([^\"]+)\">");
        Matcher matcher = pattern.matcher(content);

        StringBuffer result = new StringBuffer();
        while (matcher.find()) {
            String pardefName = matcher.group(1);
            String converted = convertPardefName(pardefName, targetScript);
            matcher.appendReplacement(result,
                "<pardef n=\"" + Matcher.quoteReplacement(converted) + "\">");
        }
        matcher.appendTail(result);

        // Also convert in <par n="..."/> references
        pattern = Pattern.compile("<par n=\"([^\"]+)\"/>");
        matcher = pattern.matcher(result.toString());

        result = new StringBuffer();
        while (matcher.find()) {
            String pardefName = matcher.group(1);
            String converted = convertPardefName(pardefName, targetScript);
            matcher.appendReplacement(result,
                "<par n=\"" + Matcher.quoteReplacement(converted) + "\"/>");
        }
        matcher.appendTail(result);

        return result.toString();
    }

    /**
     * Convert a single pardef name.
     * Format: stem/suffix__category or stem__category
     */
    private String convertPardefName(String pardefName, String targetScript) {
        // Split on __ to separate the lemma part from category
        int categoryPos = pardefName.lastIndexOf("__");
        if (categoryPos == -1) {
            // No category separator, convert entire name
            return converter.convert(pardefName, "WX", targetScript);
        }

        String lemmaPort = pardefName.substring(0, categoryPos);
        String category = pardefName.substring(categoryPos); // includes __

        // Convert the lemma part (which may contain /)
        String convertedLemma = converter.convert(lemmaPort, "WX", targetScript);

        // Keep category as-is (it's already in English)
        return convertedLemma + category;
    }

    /**
     * Command-line interface for converting monodix files.
     */
    public static void main(String[] args) {
        if (args.length < 3) {
            System.err.println("Usage: MonodixScriptConverter <input-file> <output-file> <target-script>");
            System.err.println("Example: MonodixScriptConverter bhojpuri-wx.dix bhojpuri-deva.dix Devanagari");
            System.err.println();
            System.err.println("Supported scripts:");
            WXConverter conv = new WXConverter();
            for (String script : conv.getSupportedEncodings()) {
                System.err.println("  - " + script);
            }
            System.exit(1);
        }

        String inputPath = args[0];
        String outputPath = args[1];
        String targetScript = args[2];

        try {
            MonodixScriptConverter converter = new MonodixScriptConverter();
            converter.convertFile(new File(inputPath), new File(outputPath), targetScript);

            System.out.println("\n✅ Successfully converted monodix file to " + targetScript + "!");
        } catch (Exception e) {
            System.err.println("Error converting file: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }
}
